# Generated by Django 3.2.13 on 2022-08-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='program',
            name='requirements',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='tuition',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
