# Generated by Django 3.2.13 on 2022-08-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20220805_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='application_debug',
        ),
        migrations.AddField(
            model_name='student',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
