# Generated by Django 3.2.13 on 2022-08-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_university_total_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
