# Generated by Django 3.2.13 on 2022-08-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_rename_deadline_program_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
