# Generated by Django 3.2.13 on 2022-08-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_program_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='degree_studies',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
