# Generated by Django 3.2.13 on 2022-08-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_program_degree_studies'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='degree',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
