# Generated by Django 3.2.13 on 2022-08-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_student_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='degree',
            new_name='level',
        ),
    ]
