# Generated by Django 3.2.13 on 2022-08-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_rename_degree_program_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='degree',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
